import { INftItem } from "@components/NftCard"

export const recentNfts: INftItem[] = [
  {
    imgUrl: '/images/nft-cube.png',
    link: '/marketplace/mint',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    rarity: 'Common',
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
    saleType: 'mint',
  },
  {
    link: '/marketplace/auction',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
    saleType: 'auction',
  },
  {
    link: '/marketplace/mint',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
    saleType: 'mint',
  },
  {
    link: '/marketplace/sale',
    name: 'Obsidian Cube',
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
    saleType: 'sale',
  },
  {
    link: '/marketplace/sale',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    rarity: 'Rare',
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
    saleType: 'sale',
  },
  {
    link: '/marketplace/auction',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
    saleType: 'auction',
  },
  {
    link: '/marketplace/mint',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
    saleType: 'mint',
  },
  {
    imgUrl: '/images/nft-cube.png',
    link: '/marketplace/sale',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
    saleType: 'sale',
  },
  {
    link: '/marketplace/sale',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
    saleType: 'sale',
  },
  {
    link: '/marketplace/sale',
    name: 'Obsidian Cube',
    price: 12,
    currency: 'SigUSD',
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
    saleType: 'sale',
  },
  {
    link: '/marketplace/sale',
    name: 'Obsidian Cube',
    collection: 'Wrath of Gods',
    rarity: 'Common',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
    saleType: 'sale',
  },
  {
    imgUrl: '/images/nft-cube.png',
    link: '/marketplace/sale',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    rarity: 'Common',
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
    saleType: 'sale',
  },
  {
    link: '/marketplace/sale',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    rarity: 'Common',
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
    saleType: 'sale',
  },
  {
    imgUrl: '/images/nft-cube.png',
    link: '/marketplace/sale',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
    saleType: 'sale',
  },
  {
    link: '/marketplace/auction',
    name: 'Cyber Citizen Cyber Egg #323',
    price: 25,
    currency: 'SigUSD',
    rarity: 'Common',
    collection: 'Wrath of Gods Wrath of of Gods wrath',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards Blitz Trading Cards',
    artistLink: '/users/abc',
    saleType: 'auction',
  },
  {
    imgUrl: '/images/nft-cube.png',
    link: '/marketplace/mint',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
    saleType: 'mint',
  },
  {
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    imgUrl: '/images/nft-cube.png',
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    collection: 'Wrath of Gods',
    rarity: 'Common',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    imgUrl: '/images/nft-cube.png',
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  }
]