export const recentNfts = [
  {
    imgUrl: '/images/nft-cube.png',
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    rarity: 'Common',
    saleEnd: new Date(1680216090000),
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    saleEnd: new Date(1680216090000),
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    saleEnd: new Date(1687732890000),
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    saleEnd: new Date(1687732890000),
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    rarity: 'Rare',
    saleEnd: new Date(1687732890000),
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    saleEnd: new Date(1679178533000),
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    saleEnd: new Date(1679178533000),
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    imgUrl: '/images/nft-cube.png',
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    saleEnd: new Date(1679178533000),
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    saleEnd: new Date(1679178533000),
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    price: 12,
    currency: 'SigUSD',
    saleEnd: new Date(1679178533000),
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    saleEnd: new Date(1679178533000),
    collection: 'Wrath of Gods',
    rarity: 'Common',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    imgUrl: '/images/nft-cube.png',
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    rarity: 'Common',
    saleEnd: new Date(1679178533000),
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    saleEnd: new Date(1679178533000),
    rarity: 'Common',
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    imgUrl: '/images/nft-cube.png',
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    saleEnd: new Date(1679178533000),
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    price: 25,
    currency: 'SigUSD',
    saleEnd: new Date(1679178533000),
    rarity: 'Common',
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    imgUrl: '/images/nft-cube.png',
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    saleEnd: new Date(1679178533000),
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    saleEnd: new Date(1679178533000),
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    saleEnd: new Date(1679178533000),
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    imgUrl: '/images/nft-cube.png',
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    saleEnd: new Date(1679178533000),
    collection: 'Wrath of Gods',
    rarity: 'Common',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  },
  {
    imgUrl: '/images/nft-cube.png',
    link: '/marketplace/hello',
    name: 'Obsidian Cube',
    price: 17,
    currency: 'Erg',
    saleEnd: new Date(1679178533000),
    collection: 'Wrath of Gods',
    collectionLink: '/collections/test',
    artist: 'Blitz Trading Cards',
    artistLink: '/users/abc',
  }
]